

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "Projects\QuickSnacks\QuickSnacks.Data.EF\App.config"
//     Connection String Name: "QuickSnacksDb"
//     Connection String:      "Data Source=.\SQLEXPRESS;Initial Catalog=QuickSnacksDb;Persist Security Info=True;User ID=sa;password=**zapped**;;"
// ------------------------------------------------------------------------------------------------
